=== LionelKavit/Boardgame-Library-System/Design1_user_active_loans_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "UserWithActiveLoanIDs",
    "description": "Schema to define user_active_loans array structure",
    "type": "object",
    "properties": {
      "user_id": {
        "type": "integer",
        "minimum": 1,
        "description": "Unique ID of the user"
      },
      "user_name": {
        "type": "string",
        "minLength": 3,
        "description": "Full name of the user"
      },
      "user_email": {
        "type": "string",
        "description": "Email id of user"
      },
      "user_membership_type": {
        "type": "string",
        "description": "Memership type of the user (Standard/Premium)"
      },
      "loan_id": {
        "type": "array",
        "description": "List of active loan IDs for this user (max 3)",
        "items": {
          "type": "integer",
          "minimum": 1
        },
        "maxItems": 3,  
        "uniqueItems": true  
      }
    },
    "required": ["user_id", "user_name", "loan_id"]
  }

=== LionelKavit/Boardgame-Library-System/Design1_user_active_loans.json
[
  {
    "user_id": 4,
    "user_name": "David Lee",
    "user_email": "dl@yahoo.com",
    "user_membership_type": "Premium",
    "loan_id": [4, 14]
  },
  {
    "user_id": 7,
    "user_name": "Grace Miller",
    "user_email": "gm@outlook.com",
    "user_membership_type": "Standard",
    "loan_id": [7, 17]
  }
]
